<?php

namespace DJET\GimelaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AeronefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AeronefRepository extends EntityRepository
{
}
