<?php

namespace DJET\GimelaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlancheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlancheRepository extends EntityRepository
{
}
