<?php

namespace DJET\GimelaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GmlAeronefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GmlAeronefRepository extends EntityRepository
{
    public function getNbAeronef()
    {
        $query =  $this->_em->createQuery('
         	SELECT COUNT(a)
    		FROM DJETGimelaBundle:GmlAeronef a');
    	return $query->getSingleScalarResult();
    }

    public function getNbRemorqueur()
    {
        $query =  $this->_em->createQuery('
         	SELECT COUNT(a)
    		FROM DJETGimelaBundle:GmlAeronef a
		WHERE a.aeroStatut = 1');
    	return $query->getSingleScalarResult();
    }

    public function getNbPlaneur()
    {
        $query =  $this->_em->createQuery('
         	SELECT COUNT(a)
    		FROM DJETGimelaBundle:GmlAeronef a
		WHERE a.aeroStatut = 0');
    	return $query->getSingleScalarResult();
    }

    public function findFilteredAeronef($selection)
    {
	$remorqueur = $selection->getRemorqueur();
	$planeur = $selection->getPlaneur();
	
	if (($remorqueur + $planeur) == 0)
        	$query =  $this->_em->createQuery('
                	SELECT a
                	FROM DJETGimelaBundle:GmlAeronef a
                	WHERE a.aeroStatut=1 AND a.aeroStatut=0');
	else if (($remorqueur + $planeur) == 2) 
                $query =  $this->_em->createQuery('
                        SELECT a
                        FROM DJETGimelaBundle:GmlAeronef a
                        WHERE a.aeroStatut=1 OR a.aeroStatut=0');
        else if ($remorqueur == 1 && $planeur == 0)
                $query =  $this->_em->createQuery('
                        SELECT a
                        FROM DJETGimelaBundle:GmlAeronef a
                        WHERE a.aeroStatut=1');
	else
                $query =  $this->_em->createQuery('
                        SELECT a
                        FROM DJETGimelaBundle:GmlAeronef a
                        WHERE a.aeroStatut=0');
	/*
	$query=this->findBy(
		array('aeroStatut' => $remorqueur, 'aeroStatut' => $planeur),
		0,
		0,
		0
	);
	*/
        return $query->getResult();
    }



}
