<?php

namespace DJET\GimelaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GmlPlancheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GmlPlancheRepository extends EntityRepository
{
}
