<?php

namespace DJET\GimelaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GmlTarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GmlTarifRepository extends EntityRepository
{
}
